name: Codespace Execution Every 6 Hours

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  start-codespace:
    runs-on: ubuntu-latest
    steps:
      # Install GitHub CLI (if not already installed)
      - name: Install GitHub CLI
        run: |
          if ! gh --version; then
            sudo apt-get update && sudo apt-get install gh -y
          fi

      # Authenticate using the Personal Access Token stored as a secret
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.CODESPACES_TOKEN }}" | gh auth login --with-token

      # Start the specific Codespace directly using the known name
      - name: Start Codespace
        run: gh codespace start --repo aman-rlf/rentlondonflat-pipeline --codespace stunning-winner-jjqrgg97pw4p2q97j

      # Wait for Codespace to be ready
      - name: Wait for Codespace to start
        run: sleep 10

      # Execute the pipeline script inside the Codespace
      - name: Execute Pipeline Script
        run: gh codespace ssh --command "python3 /workspaces/rentlondonflat-pipeline/sql_database_pipeline.py" --codespace stunning-winner-jjqrgg97pw4p2q97j

      # Stop the Codespace after running the script
      - name: Stop Codespace
        if: always()
        run: gh codespace stop --repo aman-rlf/rentlondonflat-pipeline --codespace stunning-winner-jjqrgg97pw4p2q97j
