name: Codespace Execution Every 6 Hours

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:       # Allows manual triggering

jobs:
  start-codespace:
    runs-on: ubuntu-latest
    steps:
      # Install GitHub CLI using the official repository for the latest version
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      # Authenticate using the Personal Access Token stored as a secret
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.CODESPACES_TOKEN }}" | gh auth login --with-token

      # Start the specific Codespace (Option 1: Create or Reuse)
      - name: Start Codespace
        run: |
          gh codespace create --repo aman-rlf/rentlondonflat-pipeline --name stunning-winner-jjqrgg97pw4p2q97j --branch main --machine "standardLinux"

      # Wait for Codespace to be ready (optional: implement a more robust wait)
      - name: Wait for Codespace to start
        run: sleep 25

      # Get Codespace Name (Already known, but ensures correct retrieval)
      - name: Get Codespace Name
        run: |
          CODESPACE_NAME=$(gh codespace list --repo aman-rlf/rentlondonflat-pipeline --json name,state -q '.[] | select(.name == "stunning-winner-jjqrgg97pw4p2q97j") | .name')
          echo "CODESPACE_NAME=${CODESPACE_NAME}" >> $GITHUB_ENV

      # Execute the pipeline script inside the Codespace (Option 2: SSH)
      - name: Execute Pipeline Script
        run: |
          gh codespace ssh --codespace "${CODESPACE_NAME}" --command "bash /path/to/your/pipeline-script.sh"
