name: Codespace Execution Every 6 Hours

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:       # Allows manual triggering

jobs:
  start-codespace:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.CODESPACES_TOKEN }}  # Set GH_TOKEN environment variable
    steps:
      # Install GitHub CLI using the official repository for the latest version
      - name: Install GitHub CLI
        run: |
          # Install curl if not present
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          
          # Add GitHub CLI GPG key and repository
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          
          # Update and install gh
          sudo apt update
          sudo apt install gh -y

      # Verify Authentication
      - name: Verify GitHub CLI Authentication
        run: gh auth status

      # Start the specific Codespace using the correct flags and machine type
      - name: Start Codespace
        run: |
          gh codespace create \
            --repo aman-rlf/rentlondonflat-pipeline \
            --display-name stunning-winner-jjqrgg97pw4p2q97j \
            --branch main \
            --machine "standardLinux32gb"

      # Wait for Codespace to be ready
      - name: Wait for Codespace to Start
        run: sleep 10

      # Retrieve the Codespace Name (Ensures the Codespace is correctly identified)
      - name: Get Codespace Name
        run: |
          CODESPACE_NAME=$(gh codespace list --repo aman-rlf/rentlondonflat-pipeline --json name,state -q '.[] | select(.name == "stunning-winner-jjqrgg97pw4p2q97j") | .name')
          echo "CODESPACE_NAME=${CODESPACE_NAME}" >> $GITHUB_ENV

      # Execute the pipeline script inside the Codespace
      - name: Execute Pipeline Script
        run: |
          gh codespace ssh --codespace "${CODESPACE_NAME}" --command "bash /path/to/your/pipeline-script.sh"
