name: Codespace Execution Every 6 Hours

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  start-codespace:
    runs-on: ubuntu-latest
    steps:
      # Install GitHub CLI using the official repository for the latest version
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      # Authenticate using the Personal Access Token stored as a secret
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.CODESPACES_TOKEN }}" | gh auth login --with-token

      # Start the specific Codespace directly using the known name
      - name: Start Codespace
        run: gh codespace start --codespace stunning-winner-jjqrgg97pw4p2q97j

      # Wait for Codespace to be ready
      - name: Wait for Codespace to start
        run: sleep 10

      # Get Codespace ID (using name if ID is unavailable)
      - name: Get Codespace ID
        run: |
          CODESPACE_NAME="stunning-winner-jjqrgg97pw4p2q97j"
          CODESPACE_ID=$(gh codespace list --repo aman-rlf/rentlondonflat-pipeline --json name,state -q ".[] | select(.name == \"${CODESPACE_NAME}\") | .name")
          echo "CODESPACE_ID=${CODESPACE_ID}" >> $GITHUB_ENV

      # Execute the pipeline script inside the Codespace
      - name: Execute Pipeline Script
        run: |
          gh codespace ssh --codespace "${CODESPACE_ID}" --command "bash /path/to/your/pipeline-script.sh"
