name: Codespace Execution Every 6 Hours

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:       # Allows manual triggering

jobs:
  start-codespace:
    runs-on: ubuntu-latest
    steps:
      # 1. Setup GitHub CLI using the official action
      - name: Setup GitHub CLI
        uses: cli/setup-gh@v2
        with:
          version: latest  # Ensures the latest version is installed

      # 2. Authenticate GitHub CLI non-interactively using the PAT
      - name: Authenticate GitHub CLI
        env:
          CODESPACES_TOKEN: ${{ secrets.CODESPACES_TOKEN }}
        run: echo "$CODESPACES_TOKEN" | gh auth login --with-token

      # 3. Verify Authentication
      - name: Verify GitHub CLI Authentication
        run: gh auth status

      # 4. Start the specific Codespace using correct flags and machine type
      - name: Start Codespace
        run: |
          gh codespace create \
            --repo aman-rlf/rentlondonflat-pipeline \
            --display-name stunning-winner-jjqrgg97pw4p2q97j \
            --branch main \
            --machine "standardLinux32gb"

      # 5. Wait for Codespace to be ready (implement a robust wait if necessary)
      - name: Wait for Codespace to Start
        run: sleep 10  # Optional: Replace with a loop checking Codespace status

      # 6. Retrieve the Codespace Name
      - name: Get Codespace Name
        run: |
          CODESPACE_NAME=$(gh codespace list --repo aman-rlf/rentlondonflat-pipeline --json name,displayName,state -q '.[] | select(.displayName == "stunning-winner-jjqrgg97pw4p2q97j") | .name')
          echo "CODESPACE_NAME=${CODESPACE_NAME}" >> $GITHUB_ENV

      # 7. Execute the pipeline script inside the Codespace
      - name: Execute Pipeline Script
        run: |
          gh codespace ssh --codespace "${CODESPACE_NAME}" --command "bash /path/to/your/pipeline-script.sh"
